### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by rkarim0598** [rkarim0598/not-tiNDer#24]
General cleaning up of code/refactoring

**Comment by johnameyer** [comment]
Including but not limited to:

- Removing extraneous / unused files
- Restructuring folders to make more sense
- Utilizing more specific errors on the backend
- Use more idiomatic vue

**Comment by johnameyer** [comment]
Are we using / should we use Vuex?
Should we move files into the graphql folder on client side?

**Comment by rkarim0598** [comment]
Depends if/how we implement global listening for messages in #34. I'm assuming by moving files into the graphql folder, you mean just moving the queries?  I'm a bit indifferent concerning that.

**Comment by johnameyer** [comment]
Yeah moving the queries - should make the code look a little cleaner
