### ISSUE TITLE
Matches subscription

### ISSUE THREAD

**Issue by johnameyer** [rkarim0598/not-tiNDer#34]
The matches page should update when new messages arrive (perhaps with a notification dot)

**Comment by rkarim0598** [comment]
Are you thinking this happens when you're explicitly on the Matches page, or are you thinking that you'd just see a dot pop up by the icon in the bottom nav bar wherever you are in the app?

**Comment by johnameyer** [comment]
Both if possible, though I realize as we don't really have a global state in Vue the latter would be difficult

**Comment by rkarim0598** [comment]
Couple ways we could do it if we wanted, Vuex has a little bit of a learning curve but I believe it would do the job.  We also might be able to just use regular state and props and listen for messages in App.vue similar to how we currently subscribe in Messages and then pass the data through props (might have to be route params, but I'm not certain).
